/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SituationRoomRouteImport } from './routes/situation-room'
import { Route as WelfareCheckRouteImport } from './routes/welfare-check'
import { Route as WelfareHistoryRouteImport } from './routes/welfare-history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationRoomRoute = SituationRoomRouteImport.update({
  id: '/situation-room',
  path: '/situation-room',
  getParentRoute: () => rootRouteImport,
} as any)
const WelfareCheckRoute = WelfareCheckRouteImport.update({
  id: '/welfare-check',
  path: '/welfare-check',
  getParentRoute: () => rootRouteImport,
} as any)
const WelfareHistoryRoute = WelfareHistoryRouteImport.update({
  id: '/welfare-history',
  path: '/welfare-history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/home': typeof HomeRoute
  '/safety': typeof SafetyRoute
  '/situation-room': typeof SituationRoomRoute
  '/welfare-check': typeof WelfareCheckRoute
  '/welfare-history': typeof WelfareHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/home': typeof HomeRoute
  '/safety': typeof SafetyRoute
  '/situation-room': typeof SituationRoomRoute
  '/welfare-check': typeof WelfareCheckRoute
  '/welfare-history': typeof WelfareHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/home': typeof HomeRoute
  '/safety': typeof SafetyRoute
  '/situation-room': typeof SituationRoomRoute
  '/welfare-check': typeof WelfareCheckRoute
  '/welfare-history': typeof WelfareHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacts'
    | '/home'
    | '/safety'
    | '/situation-room'
    | '/welfare-check'
    | '/welfare-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacts'
    | '/home'
    | '/safety'
    | '/situation-room'
    | '/welfare-check'
    | '/welfare-history'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contacts'
    | '/home'
    | '/safety'
    | '/situation-room'
    | '/welfare-check'
    | '/welfare-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactsRoute: typeof ContactsRoute
  HomeRoute: typeof HomeRoute
  SafetyRoute: typeof SafetyRoute
  SituationRoomRoute: typeof SituationRoomRoute
  WelfareCheckRoute: typeof WelfareCheckRoute
  WelfareHistoryRoute: typeof WelfareHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situation-room': {
      id: '/situation-room'
      path: '/situation-room'
      fullPath: '/situation-room'
      preLoaderRoute: typeof SituationRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welfare-check': {
      id: '/welfare-check'
      path: '/welfare-check'
      fullPath: '/welfare-check'
      preLoaderRoute: typeof WelfareCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welfare-history': {
      id: '/welfare-history'
      path: '/welfare-history'
      fullPath: '/welfare-history'
      preLoaderRoute: typeof WelfareHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactsRoute: ContactsRoute,
  HomeRoute: HomeRoute,
  SafetyRoute: SafetyRoute,
  SituationRoomRoute: SituationRoomRoute,
  WelfareCheckRoute: WelfareCheckRoute,
  WelfareHistoryRoute: WelfareHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
